
version: '3'

services:
  postgresdb:
    image: postgres:12
    environment:
      - POSTGRES_USER=index_demo
      - POSTGRES_PASSWORD=index_demo
      - POSTGRES_DB=index_demo_development
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    volumes:
      - ./pgadmin-data:/var/lib/postgresql/data
    ports:
      - 80:80
    networks:
      - postgres-compose-network

volumes:
  postgres-data:
    driver: local

networks: 
  postgres-compose-network:
    driver: bridge